### ISSUE TITLE
Getting an error with extract-text-webpack-plugin-output-filename

### ISSUE THREAD

**Issue by colinaut** [Regis011/wp-child-theme-v2#1]
I get this error when I npm run dev "Entrypoint undefined = extract-text-webpack-plugin-output-filename"

I'm guessing that this has to do with the fact that extract-text-webpack-plugin isn't geared for use with Webpack 4? On the GitHub page for extract-text-webpack-plugin it says that "Since webpack v4 the extract-text-webpack-plugin should not be used for css. Use mini-css-extract-plugin instead."

**Comment by Regis011** [comment]
Thanks for this @colinaut. I will fix this during the weekend or start next week.

**Comment by Regis011** [comment]
@colinaut now are child theme updated with new webpack configuration. Good luck with coding :-)
